# Generated by Django 4.2.1 on 2023-10-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='num',
        ),
    ]
